language: java
jdk:
- oraclejdk8

install: true
dist: trusty
sudo: required

cache:
  directories:
  - '$HOME/.m2/repository'

addons:
  chrome: stable

stages:
- build
- test

jobs:
  include:
  - stage: build
    script: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - stage: test
    script: mvn test -B -V
  - stage: test
    before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    script: mvn verify -DskipUnitTests=true -Djbehave.report.level=STORY -Pintegration-test -B -V
