language: java
jdk:
- oraclejdk8

install: true

cache:
  directories:
  - '$HOME/.m2/repository'

stages:
- build
- test

jobs:
  include:
  - stage: build
    script: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - stage: test
    script: mvn test -B -V
