language: java

install: true
sudo: required

cache:
  directories:
  - '$HOME/.m2'

matrix:
  include:
    - stage: build
      dist: trusty
      jdk: oraclejdk8
      env: CI_SCRIPT=ci/build.sh
    - stage: build
      dist: xenial
      jdk: openjdk11
      env: CI_SCRIPT=ci/build.sh

    - stage: test
      dist: trusty
      jdk: oraclejdk8
      env: CI_SCRIPT=ci/test.sh
    - stage: test
      dist: xenial
      jdk: openjdk11
      env: CI_SCRIPT=ci/test.sh

    - stage: system-test
      dist: trusty
      jdk: oraclejdk8
      addons:
        chrome: stable
      before_script:
        - chmod +x ci/trusty-before-system-test.sh
        - source ./ci/trusty-before-system-test.sh # we need sourcing to have the exported variables available outside of script
      env: CI_SCRIPT=ci/system-test.sh
    - stage: system-test
      dist: xenial
      jdk: openjdk11
      addons:
        chrome: stable
      services:
        - xvfb
      env: CI_SCRIPT=ci/system-test.sh

script:
  - "chmod -R +x ci"
  - "$CI_SCRIPT"
