spring:
  datasource:
    port: 11112
    url: jdbc:h2:tcp://localhost:${spring.datasource.port}/mem:test;MODE=ORACLE
    driver: org.h2.Driver
    username: sa
    password: sa

server:
  port: 11110

security:
  user:
    name: sa
    password: sa

ssh:
  port: 2000
  timeouts:
    auth: 600000
    idle: 600000
  credentials:
    user: ${security.user.name}
    password: ${security.user.password}
    key: 'classpath:/ssh/publicKey.pem'
